# Generated by Django 5.1.3 on 2024-11-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
