# Generated by Django 5.1.3 on 2024-11-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_answer_user_remove_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='country',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='school',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
