# Generated by Django 5.1.3 on 2024-11-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_school_country_remove_homework_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
